# Generated by Django 5.1 on 2025-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_child_grade_alter_class_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='ru', max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='kz', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailymessage',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='ru', max_length=50),
        ),
        migrations.AlterField(
            model_name='motivationalphrase',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='ru', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='kz', max_length=50),
        ),
    ]
