# Generated by Django 5.1 on 2025-06-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_is_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_year',
            field=models.CharField(default='2024-2025', max_length=10),
        ),
    ]
