version: "3.8"

services:
  redis:
    image: redis:6
    networks:
      - vunderkids_net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: protosedu
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: protosedu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vunderkids_net

  web:
    build: .
    command:
      [
        "gunicorn",
        "vunderkids.wsgi",
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "4"
      ]
    volumes:
      - .:/django
    ports:
      - "9000:8000"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgres://vunderkids:securepassword@db:5432/vunderkids_db
    depends_on:
      - redis
      - db
    networks:
      - vunderkids_net

  celery_worker:
    build: .
    command: celery -A vunderkids worker --loglevel=info
    volumes:
      - .:/django
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgres://vunderkids:securepassword@db:5432/vunderkids_db
    depends_on:
      - web
      - redis
      - db
    networks:
      - vunderkids_net

  celery_beat:
    build: .
    command: celery -A vunderkids beat --loglevel=info
    volumes:
      - .:/django
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgres://vunderkids:securepassword@db:5432/vunderkids_db
    depends_on:
      - web
      - redis
      - db
    networks:
      - vunderkids_net

volumes:
  postgres_data:

networks:
  vunderkids_net:
