# Generated by Django 4.2.20 on 2025-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('ktp', 'KTP')], default='ktp', max_length=64)),
                ('grade', models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
