# Generated by Django 4.2.20 on 2025-04-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/preview/'),
        ),
    ]
