# Generated by Django 5.2 on 2025-04-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_subject_remove_document_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.subject'),
            preserve_default=False,
        ),
    ]
