# Generated by Django 5.2 on 2025-04-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order']},
        ),
    ]
