# Generated by Django 5.1 on 2025-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='ru', max_length=50),
        ),
    ]
