# Generated by Django 5.1.6 on 2025-03-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_question_created_at'),
        ('tasks', '0007_alter_course_course_type'),
    ]

    operations = [
    ]
