# Generated by Django 4.2.19 on 2025-03-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_merge_20250313_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
    ]
