# Generated by Django 4.2.19 on 2025-03-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_question_question_type'),
        ('tasks', '0009_remove_question_created_at'),
    ]

    operations = [
    ]
