# Generated by Django 4.2.19 on 2025-03-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_merge_20250315_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
    ]
