# Generated by Django 4.2.19 on 2025-03-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
