# Generated by Django 5.1.6 on 2025-03-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_question_question_type'),
        ('tasks', '0013_remove_image_image_id_canvasimage'),
    ]

    operations = [
    ]
