# Generated by Django 4.2.19 on 2025-03-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_question_question_type'),
        ('tasks', '0013_remove_image_image_id_canvasimage'),
    ]

    operations = [
    ]
