# Generated by Django 4.2.13 on 2025-03-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_merge_20250324_1956'),
        ('tasks', '0015_alter_question_correct_answer_and_more'),
    ]

    operations = [
    ]
