# Generated by Django 4.2.20 on 2025-03-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_merge_20250324_2135'),
        ('tasks', '0016_merge_20250326_1930'),
    ]

    operations = [
    ]
