# Generated by Django 5.1 on 2025-04-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('content', 'Content'), ('bug', 'Bug'), ('other', 'Other')], default='bug', max_length=50),
            preserve_default=False,
        ),
    ]
