# Generated by Django 5.1 on 2025-04-15 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tasks.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tasks.task'),
            preserve_default=False,
        ),
    ]
