# Generated by Django 5.1 on 2025-05-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_course_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_nodes', to='tasks.chapter')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_node', to='tasks.lesson')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_node', to='tasks.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
