# Generated by Django 5.1 on 2025-06-03 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0007_alter_testanswer_child_alter_testanswer_user_and_more'),
        ('tasks', '0027_contentnode_description_contentnode_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='diagnostic_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_chapters', to='modo.test'),
        ),
    ]
