# Generated by Django 5.1 on 2025-06-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0007_alter_testanswer_child_alter_testanswer_user_and_more'),
        ('tasks', '0028_chapter_diagnostic_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='diagnostic_test',
        ),
        migrations.AddField(
            model_name='chapter',
            name='after_diagnostic_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_chapters_after', to='modo.test'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='before_diagnostic_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_chapters_before', to='modo.test'),
        ),
    ]
