# Generated by Django 4.2.20 on 2025-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0002_remove_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('modo', 'MODO'), ('ent', 'ENT'), ('diagnostic', 'Diagnostic'), ('other', 'Other')], default='modo', max_length=20),
        ),
    ]
