# Generated by Django 5.1 on 2025-05-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0003_alter_test_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_options/images/'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='option_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=5),
        ),
    ]
