# Generated by Django 5.1 on 2025-05-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0004_answeroption_image_answeroption_option_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
