# Generated by Django 5.1 on 2025-06-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0007_alter_testanswer_child_alter_testanswer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
    ]
