# Generated by Django 5.1 on 2025-06-05 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_is_test_user'),
        ('modo', '0008_alter_question_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='test_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='modo.testresult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('test', 'user', 'child', 'attempt_number')},
        ),
    ]
