# Generated by Django 5.1 on 2025-06-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0009_alter_testresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
