# Generated by Django 5.1 on 2025-06-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0010_test_shuffle_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_profile', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English'), ('cm', 'Common')], default='ru', max_length=10)),
                ('test_type', models.CharField(blank=True, choices=[('modo', 'MODO'), ('ent', 'ENT'), ('diagnostic', 'Diagnostic'), ('pisa', 'PISA'), ('other', 'Other')], default='modo', max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('modo', 'MODO'), ('ent', 'ENT'), ('diagnostic', 'Diagnostic'), ('pisa', 'PISA'), ('other', 'Other')], default='modo', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='modo.testcategory'),
        ),
    ]
