# Generated by Django 5.1 on 2025-07-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0013_alter_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='answer_options/images/'),
        ),
    ]
