# Generated by Django 5.1 on 2025-07-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0014_alter_answeroption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open Ended')], default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answer_options/images/'),
        ),
    ]
