# Generated by Django 5.1 on 2025-07-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0015_question_correct_answer_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open')], default='mcq', max_length=10),
        ),
    ]
