# Generated by Django 5.1 on 2025-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0016_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('mcq', 'Multiple Choice'), ('open', 'Open')], default='mcq', max_length=10, null=True),
        ),
    ]
