# Generated by Django 5.1 on 2025-07-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modo', '0015_alter_answeroption_image'),
        ('modo', '0017_alter_question_type'),
    ]

    operations = [
    ]
