# Generated by Django 5.2 on 2025-04-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0013_dailymessage_motivationalphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rank', models.IntegerField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='league_icons/')),
                ('max_players', models.IntegerField(default=30)),
                ('promotions_rate', models.IntegerField()),
                ('demotions_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='LeagueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='leagues.league')),
            ],
            options={
                'verbose_name': 'League Student Group',
                'verbose_name_plural': 'League Student Groups',
                'ordering': ['league', 'group_name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueGroupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cups_earned', models.IntegerField(db_index=True, default=0)),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.child')),
                ('league_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='leagues.leaguegroup')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name': 'League Group Participant',
                'verbose_name_plural': 'League Group Participants',
                'ordering': ['-cups_earned'],
                'unique_together': {('league_group', 'student', 'child')},
            },
        ),
    ]
