# Generated by Django 5.1 on 2025-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='rank',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
