# Generated by Django 5.1 on 2025-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_league_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguegroupparticipant',
            name='rank',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
