name: Deploy with Docker Compose

on:
  push:
    branches: [ test-github-actions ]  # Runs only on this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VPS and restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: protosedu2024
          port: 22
          script: |
            cd /home/protosedu/protosedu-prod/protosedu-backend
            git checkout -b test-github-actions
            git pull origin test-github-actions
            docker compose down
            docker compose up --build -d
