name: Debug Secrets

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secrets (Without Exposing)
        run: |
          echo "Checking Secrets..."
          echo "SERVER_HOST: ${{ secrets.SERVER_HOST }}"
          echo "SERVER_USER: ${{ secrets.SERVER_USER }}"
          echo "SERVER_SSH_KEY Length: $(echo "${{ secrets.SERVER_SSH_KEY }}" | wc -c)"
          echo "SERVER_SSH_KEY: $(echo "${{ secrets.SERVER_SSH_KEY }}" | head -c 100)..."