name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH and Connect with Password
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -t -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "bash -c 'echo Debug: Connecting to server && cd "${{ secrets.WORK_DIR }}" && echo Debug: Changed directory to ${{ secrets.WORK_DIR }} && ls -l'"