name: Deploy Backend

on:
  push:
    branches: ["prod"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: prod

      - name: Pull the latest code
        run: git pull origin prod

      - name: Trigger deployment workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: BekzhanK1/vunderkids
          event-type: backend-updated
